import type { Metadata } from "next";
import { Orbitron, Carrois_Gothic_SC } from "next/font/google";
import "./globals.css";

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  weight: ["500", "700"],
  display: "swap",
});

const carrois = Carrois_Gothic_SC({
  variable: "--font-carrois",
  subsets: ["latin"],
  display: "swap",
  weight: "400"
});


export const metadata: Metadata = {
  title: "Rohith Yarramala | CEO @ Renitiate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${orbitron.variable} ${orbitron.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
